name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  rpi-docker-build:

    runs-on: ubuntu-latest

    steps:
    -
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - uses: actions/checkout@v3
    - name: Build the RPi Docker image
      run: docker compose build rpi && docker compose push rpi
